#!/usr/bin/env ruby
#encoding: UTF-8

require 'sass'

(Dir["./assets/scss/*.scss"]).each do |item|
    target = "./assets/css/" + File.basename(item,".*") + ".css"
    puts "converting " + item + " to " + target
    Sass.compile_file( item , target) 
    system "git add " + target
end
